ktor {
  deployment {
    port = 8080
    port = ${?PORT}
  }

}

jwt {
  issuer = ${?JWT_ISSUER}
  audience = ${?JWT_AUDIENCE}
  secret = ${?JWT_SECRET}
  ttlSeconds = ${?JWT_TTL_SECONDS}
}

google {
  clientId = ${?GOOGLE_CLIENT_ID}
  clientSecret = ${?GOOGLE_CLIENT_SECRET}
}

app {
  publicBackendBaseUrl = ${?PUBLIC_BACKEND_BASE_URL}
  frontendBaseUrl = ${?FRONTEND_BASE_URL}
  authCookieSecure = ${?AUTH_COOKIE_SECURE}
  authCookieSameSite = ${?AUTH_COOKIE_SAME_SITE}
}
